#!/usr/bin/env python3
"""KTAI venv setup — gives KTAI its own isolated runtime.

Clones the Hermes venv (308 MB of already-installed dependencies: litellm, openai,
fastapi, discord.py, ...) into ~/KTAI/venv and repoints every absolute path from
the Hermes install to the KTAI core. That avoids re-downloading/re-resolving the
whole dependency tree while keeping KTAI's runtime fully independent: after this
step nothing in KTAI reads or writes ~/.hermes/hermes-agent.

Why repointing works: the venv's editable install is a `__editable__*.pth` +
finder module whose MAPPING/NAMESPACES tables hold absolute source paths. Rewriting
that table (and the console-script shebangs) is enough to move the install root.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

KTAI_ROOT = Path(__file__).resolve().parent.parent
SRC_VENV = Path.home() / ".hermes" / "hermes-agent" / "venv"
DST_VENV = KTAI_ROOT / "venv"
CORE = KTAI_ROOT / "core"
OLD_ROOT = str((Path.home() / ".hermes" / "hermes-agent").resolve())
NEW_ROOT = str(CORE.resolve())


def step(msg: str) -> None:
    print(f"== {msg}")


def main() -> int:
    if not SRC_VENV.is_dir():
        print(f"source venv not found: {SRC_VENV}")
        return 1

    if DST_VENV.exists():
        step(f"removing previous venv at {DST_VENV}")
        shutil.rmtree(DST_VENV)

    step(f"cloning venv {SRC_VENV} -> {DST_VENV} (308 MB, preserves symlinks)")
    subprocess.run(["cp", "-a", str(SRC_VENV), str(DST_VENV)], check=True)

    step("repointing absolute paths (editable finder, shebangs, activate scripts)")
    rewritten, scanned = 0, 0
    for path in DST_VENV.rglob("*"):
        if not path.is_file() or path.is_symlink():
            continue
        try:
            if path.stat().st_size > 3_000_000:
                continue
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue  # binary payloads (.so, .dylib) — never touch
        scanned += 1
        # `OLD_ROOT/venv` must be rewritten first: console-script shebangs
        # (`#!/…/hermes-agent/venv/bin/python3`) point at the venv, not the source
        # tree, so a plain OLD_ROOT→NEW_ROOT swap would leave them dangling.
        new_text = text.replace(f"{OLD_ROOT}/venv", str(DST_VENV))
        if OLD_ROOT in new_text:
            new_text = new_text.replace(OLD_ROOT, NEW_ROOT)
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            rewritten += 1
    step(f"text files scanned: {scanned}, repointed: {rewritten}")

    # The editable finder for the KTAI core must win over any stale mapping.
    site = next(DST_VENV.glob("lib/python3*/site-packages"))
    for junk in list(site.glob("__editable__*")):
        junk.unlink()
    (site / "ktai_core.pth").write_text(
        f"{NEW_ROOT}\n{KTAI_ROOT}\n", encoding="utf-8")
    step(f"editable mapping replaced by {site / 'ktai_core.pth'}")

    # Console scripts: keep the passthrough faithful (argv[0] still reads 'ktai'
    # because the launcher execs with that name).
    binp = DST_VENV / "bin"
    ktai_script = binp / "ktai"
    ktai_script.write_text(
        f"""#!/bin/sh
# KTAI entry point (generated by scripts/setup_venv.py)
KTAI_HOME="${{KTAI_HOME:-$HOME/.ktai}}"
export KTAI_HOME
export HERMES_HOME="$KTAI_HOME"
unset PYTHONPATH PYTHONHOME
exec "{binp}/python3" "{KTAI_ROOT}/bin/ktai_entry.py" "$@"
""", encoding="utf-8")
    ktai_script.chmod(0o755)

    # Verification: imports must resolve inside the KTAI core, not the Hermes one.
    step("verifying import resolution")
    probe = subprocess.run(
        [str(binp / "python3"), "-c",
         "import cli, ktai_branding, hermes_constants, agent.prompt_builder as p, tools;"
         "print('cli      ->', cli.__file__);"
         "print('branding ->', ktai_branding.__file__);"
         "print('identity ->', 'You are KTAI' in p.DEFAULT_AGENT_IDENTITY)"],
        cwd=str(CORE), capture_output=True, text=True)
    print(probe.stdout.strip() or probe.stderr.strip())
    if probe.returncode != 0:
        return 1
    if NEW_ROOT not in probe.stdout:
        print("FAIL: modules resolved outside the KTAI core")
        return 1
    step("venv ready")
    return 0


if __name__ == "__main__":
    sys.exit(main())
